# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'extrusion.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_extrusion_window(object):
    def setupUi(self, extrusion_window):
        sizeObject = QtWidgets.QDesktopWidget().screenGeometry(-1)
        screen_height = sizeObject.height()
        screen_width = sizeObject.width()
        extrusion_window.setObjectName("extrusion_window")
        extrusion_window.setWindowModality(QtCore.Qt.NonModal)
        extrusion_window.resize(1280, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(extrusion_window.sizePolicy().hasHeightForWidth())
        extrusion_window.setSizePolicy(sizePolicy)
        extrusion_window.setMinimumSize(QtCore.QSize(1280, 720))
        extrusion_window.setMaximumSize(QtCore.QSize(screen_width, screen_height-60))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        extrusion_window.setFont(font)
        self.centralwidget = QtWidgets.QWidget(extrusion_window)
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.centralwidget.setObjectName("centralwidget")
        self.extr_tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.extr_tabs.setMovable(True)
        self.extr_tabs.setEnabled(True)
        self.extr_tabs.setGeometry(QtCore.QRect(10, 10, 1260, 720)) ##### !!!!!
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.extr_tabs.sizePolicy().hasHeightForWidth())
        self.extr_tabs.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.extr_tabs.setFont(font)
        self.extr_tabs.setObjectName("extr_tabs")
        # stylesheet = """
        #     QTabBar::tab:selected {background: gray;}
        #     QTabWidget>QWidget>QWidget{background: gray;}
        #     """
        # self.extr_tabs.setStyleSheet(stylesheet)
        self.tab = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        extrusion_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(extrusion_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        extrusion_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(extrusion_window)
        self.statusbar.setObjectName("statusbar")
        extrusion_window.setStatusBar(self.statusbar)
        self.start_shift = QtWidgets.QAction(extrusion_window)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.start_shift.setFont(font)
        self.start_shift.setObjectName("start_shift")
        self.end_shift = QtWidgets.QAction(extrusion_window)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.end_shift.setFont(font)
        self.end_shift.setObjectName("end_shift")
        self.menu.addAction(self.start_shift)
        self.menu.addAction(self.end_shift)
        self.menu.addSeparator()
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(extrusion_window)
        self.extr_tabs.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(extrusion_window)

    def retranslateUi(self, extrusion_window):
        _translate = QtCore.QCoreApplication.translate
        extrusion_window.setWindowTitle(_translate("extrusion_window", "Экструзия"))
        self.menu.setTitle(_translate("extrusion_window", "Смена"))
        self.start_shift.setText(_translate("extrusion_window", "Начать смену"))
        self.end_shift.setText(_translate("extrusion_window", "Закончить смену"))
