# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'authorize.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login_Dialog(object):
    def setupUi(self, login_Dialog):
        login_Dialog.setObjectName("login_Dialog")
        login_Dialog.setEnabled(True)
        login_Dialog.resize(283, 130)
        login_Dialog.setMinimumSize(QtCore.QSize(283, 130))
        login_Dialog.setMaximumSize(QtCore.QSize(350, 130))
        self.gridLayout = QtWidgets.QGridLayout(login_Dialog)
        self.gridLayout.setVerticalSpacing(3)
        self.gridLayout.setObjectName("gridLayout")
        self.exit_button = QtWidgets.QPushButton(login_Dialog)
        font = QtGui.QFont()
        font.setFamily("Amazon Ember Display")
        font.setPointSize(10)
        self.exit_button.setFont(font)
        self.exit_button.setObjectName("exit_button")
        self.gridLayout.addWidget(self.exit_button, 2, 3, 1, 1)
        self.login_button = QtWidgets.QPushButton(login_Dialog)
        font = QtGui.QFont()
        font.setFamily("Amazon Ember Display")
        font.setPointSize(10)
        self.login_button.setFont(font)
        self.login_button.setObjectName("login_button")
        self.gridLayout.addWidget(self.login_button, 2, 2, 1, 1)
        self.password_field = QtWidgets.QLineEdit(login_Dialog)
        self.password_field.setMinimumSize(QtCore.QSize(0, 27))
        font = QtGui.QFont()
        font.setFamily("Amazon Ember Display")
        font.setPointSize(10)
        self.password_field.setFont(font)
        self.password_field.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_field.setObjectName("password_field")
        self.gridLayout.addWidget(self.password_field, 1, 2, 1, 2)
        self.comboBox = QtWidgets.QComboBox(login_Dialog)
        self.comboBox.setMinimumSize(QtCore.QSize(0, 27))
        font = QtGui.QFont()
        font.setFamily("Amazon Ember Display")
        font.setPointSize(10)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 0, 2, 1, 2)
        self.user_input_label = QtWidgets.QLabel(login_Dialog)
        font = QtGui.QFont()
        font.setFamily("Amazon Ember Display")
        font.setPointSize(10)
        self.user_input_label.setFont(font)
        self.user_input_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.user_input_label.setObjectName("user_input_label")
        self.gridLayout.addWidget(self.user_input_label, 0, 0, 1, 1)
        self.pass_input_label = QtWidgets.QLabel(login_Dialog)
        font = QtGui.QFont()
        font.setFamily("Amazon Ember Display")
        font.setPointSize(10)
        self.pass_input_label.setFont(font)
        self.pass_input_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pass_input_label.setObjectName("pass_input_label")
        self.gridLayout.addWidget(self.pass_input_label, 1, 0, 1, 1)

        self.retranslateUi(login_Dialog)
        QtCore.QMetaObject.connectSlotsByName(login_Dialog)

    def retranslateUi(self, login_Dialog):
        _translate = QtCore.QCoreApplication.translate
        login_Dialog.setWindowTitle(_translate("login_Dialog", "FPS - Авторизация"))
        self.exit_button.setText(_translate("login_Dialog", "Закрыть"))
        self.login_button.setText(_translate("login_Dialog", "Вход"))
        self.user_input_label.setText(_translate("login_Dialog", "Пользователь:"))
        self.pass_input_label.setText(_translate("login_Dialog", "Пароль:"))
