# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'name_combobox.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.name_comboBox = QtWidgets.QComboBox(Form)
        self.name_comboBox.setGeometry(QtCore.QRect(70, 90, 1000, 31))
        self.name_comboBox.setMinimumSize(QtCore.QSize(1000, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(14)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.name_comboBox.setFont(font)
        self.name_comboBox.setObjectName("name_comboBox")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
